GET http://localhost:3000/signup

###

POST http://localhost:3000/login
content-type: application/json

{
    "email":"vbelwal@gmail.com",
    "password":"hellopassword"
}


###


POST http://localhost:3000/signup
content-type: application/json

{
    "email":"perseveranceCF@gmail.com",
    "password":"123456"
}